<?php
$ticketid = $this->getRequest()->getParam('id');
$collection_tickets = Mage::getModel('imedia_ticketsupport/support')->getCollection();
$collection_tickets->addFieldToFilter( 'id', $ticketid );

$collection = Mage::getModel('imedia_ticketsupport/details')->getCollection();
$collection->addFieldToFilter('ticketid', $ticketid );
$collection->getSelect()->order('commentdate desc');
?>

<?php if($collection->count()): ?>

<div class="page-title">
  <h1>[Ticket # <?php echo $collection_tickets->getFirstItem()->getId();?>] <?php echo $collection_tickets->getFirstItem()->getTitle();?></h1>
</div>

<div class="fieldset">
  <h2 class="legend">Ticket Information</h2>
  <table cellspacing="0" class="form-list">
		<tbody>
			<tr>
			  <td align="left" class="label" width="140">Department: </td>
			  <td><strong><?php echo $collection_tickets->getFirstItem()->getDept();?></strong></td>
			  <td align="right" width="250"><a href="<?php echo Mage::helper("adminhtml")->getUrl("*/*/closeticket",array("id"=>$ticketid)) ?>"> Close this ticket </a></td>
			</tr>
			<tr>
			  <td align="left" class="label">Status:</td>
			  <td align="left"><strong><?php echo $collection_tickets->getFirstItem()->getStatus();?></strong></td>
			  <td>&nbsp;</td>
			</tr>
		  </tbody>
		</table>
</div>

    
<table class="data-table" id="ticket-table">
  <colgroup><col width="15%">
  <col>
  <col width="15%">
  </colgroup><thead>
    <tr>
      <th>Sender</th>
      <th>Message</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($collection as $item): ?>
    <tr>
      <td><?php echo $item->getSender();?></td>
      <td><?php echo $item->getComments();?><br>
        </td>
      <td><?php echo $item->getcommentdate();?></td>
    </tr>
	<?php endforeach; ?> 
      </tbody>
</table>

 <script>
    function validate()
    {
      if(document.getElementById("content").value==null || document.getElementById("content").value=="")
	  {
		   alert("Comment field can't be left blank");
		  return false;
	  }
    } 
   </script>  
<div class="clearfix">&nbsp;</div>
<form action="<?php echo $this->getFormAction(); ?>" method="post" id="form-send-reply1" enctype="multipart/form-data" onsubmit="return validate();">
   <input type="hidden" name="form_key" value="<? echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
  <div class="fieldset">
    <h2 class="legend">Reply</h2>
    <div class="form-list">
      <label for="content" class="required">Message<em>*</em></label>
      <div class="input-box">
        <textarea name="content" id="content" title="Message" class="input-text required-entry" style="width:545px"></textarea>
      </div>
    </div>
    <div class="buttons-set button-send">
      <p class="required">* Required Fields</p>
      <button type="submit" title="Send" class="button" ><span><span>Send</span></span></button>
    </div>
  </div>
</form>

<?php else: ?>
<div class="page-title">
  <h3>This ticket has been closed or not found</h3>
</div>
<?php endif; ?>