<?php
$collection = $this->getCollection();
if($collection->count()!= 0):
?>

<div class="page-title">
	<h1>My Tickets</h1>
</div>

<?php echo $this->getPagerHtml(); ?>
    
<table class="data-table" id="tickets-table">
    <colgroup><col width="1">
    <col>
    <col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
    </colgroup><thead>
        <tr>
        <th>Ticket #</th>
	    <th>Title</th>
	    <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
            <th>Department</th>
            <th>Priority</th>
            <th><span class="nobr">Status</span></th>
            <th><span class="nobr">Replies</span></th>
        </tr>
    </thead>
    <tbody>
	<?php foreach($collection as $item): ?>
		<tr>
			<td class="a-center"><?php echo $item->getId();?></td>
			<td><a href="<?php echo $this->getUrl('ticketsupport/index/viewticket').'?id='.$item->getId(); ?>"><?php echo $item->getTitle();?></a></td>
			<td class="a-center"><?php echo $item->getCreatedAt();?></td>
			<td class="a-center"><?php echo $item->getDept();?></td>
			<td class="a-center"><?php echo $item->getPriority();?></td>
			<td class="a-center"><?php echo $item->getStatus();?></td>
			<?php 
				$collection = Mage::getModel('imedia_ticketsupport/details')->getCollection();
				$collection->addFieldToFilter('ticketid', $item->getId() );
				$total_replies = $collection->count()-1;
			?>
			<td class="a-center"><?php echo $total_replies; ?></td>
		</tr>

		<?php endforeach; ?>
			</tbody>
</table>

       
		
<?php echo $this->getPagerHtml(); ?>
    

<?php else: ?>
<div class="page-title">
  <h3>No ticket found</h3>
</div>
<?php endif;?>